spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/lotterydraw?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: pinduoduo
      password: iagOtHmB8t2tthZT
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        stat-view-servlet:
          enabled: true
          login-username: root
          login-password: root
          url-pattern: /druid
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 50
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      use-global-data-source-stat: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com:
      huizhe:
        pinduoduo:
          mapper: debug

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST,PUT,OPTIONS,DELETE,PATCH"

